env:
  browser: true
  commonjs: true
extends:
  - 'plugin:react/recommended'
  - 'airbnb-base'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 10
plugins:
  - react
rules:   
  no-underscore-dangle: 0
  no-console: 0
  react/prop-types: 0
  